### ISSUE TITLE
Nested resource icon for expand/collapse

### ISSUE THREAD

**Issue by aetasoul** [stefanuebe/vaadin_fullcalendar#70]
Hi Stefan,
As you can see in this picture, the icon for expand/collapse the resources is not visible:

![no-icon](https://user-images.githubusercontent.com/15131692/92099553-f0fd3180-edda-11ea-97ef-862fed4849f0.JPG)

On the fullcalendar demo page those icons are present:

![yes-collapse-icon](https://user-images.githubusercontent.com/15131692/92099739-2bff6500-eddb-11ea-9533-e4237c701aef.JPG)
![yes-expand-icon](https://user-images.githubusercontent.com/15131692/92099744-2d309200-eddb-11ea-90ed-d89611c482ef.JPG)

Inspecting the HTML on the demo page I see that the class `fc-icon-plus-square` is assigned to the `span`:

`<span class="fc-icon fc-icon-plus-square"></span>`

On my calendar I have the same:

`<span class="fc-icon fc-icon-plus-square"></span>`

I think we have missed something when we created this, did you know how to fix it?

**Comment by stefanuebe** [comment]
Have you maybe changed fonts or something else regarding cosmetic / theming aspects?

**Comment by aetasoul** [comment]
Yes, but looking on your demo they are also missing

![Screenshot_20200915-094728](https://user-images.githubusercontent.com/15131692/93181282-93e97000-f738-11ea-9cab-8ad714b74ba4.jpg)

**Comment by aetasoul** [comment]
Seems that the rendering can't understand the icons, here the css:

FC CSS:
```css
.fc-icon-chevron-left:before{content:""}
.fc-icon-chevron-right:before{content:""
}.fc-icon-chevrons-left:before{content:""}
.fc-icon-chevrons-right:before{content:""}
.fc-icon-minus-square:before{content:""}
.fc-icon-plus-square:before{content:""}
.fc-icon-x:before{content:""}
```

Your CSS
```css
.fc-icon-chevron-left:before { content: var(--fc-icon-chevron-left_COLON_before-content, ""); }
.fc-icon-chevron-right:before { content: var(--fc-icon-chevron-right_COLON_before-content, ""); }
.fc-icon-chevrons-left:before { content: var(--fc-icon-chevrons-left_COLON_before-content, ""); }
.fc-icon-chevrons-right:before { content: var(--fc-icon-chevrons-right_COLON_before-content, ""); }
.fc-icon-minus-square:before { content: var(--fc-icon-minus-square_COLON_before-content, ""); }
.fc-icon-plus-square:before { content: var(--fc-icon-plus-square_COLON_before-content, ""); }
.fc-icon-x:before { content: var(--fc-icon-x_COLON_before-content, ""); }
```

I'll open a pull request as soon as possible with the fix.
